### ISSUE TITLE
FME COİN

### ISSUE THREAD

**Issue by Muslera01** [Tech-Audit/Smart-Contract-Audits#1]
FME COİN ÖN SATIŞTAN ALDIM TRUST WALLATTAKİ HESABIMDAN PARAYI ÇEKTİ VE ÖN SATIŞ BİTTİKTEN SONRA COİNLERİMİ GERİ VERMEDİ

**Comment by maungmyathar** [comment]
Ok

**Comment by Saifullah313452** [comment]
0x491390b7b4ab48F98C8A1Dc78b447CAA61b86Bfd
