### ISSUE TITLE
Fake Meme Chain Capital

### ISSUE THREAD

**Issue by mechavelli** [Tech-Audit/Smart-Contract-Audits#3]
MoonRock devs confirmed it's a fake token in their Telegram. How could Tech-Audit get outplayed like this?

**Comment by sholadavies** [comment]
> 

Can you explain what you mean? Are talking about Valentine Floki?

**Comment by RanggaYAF** [comment]
What do you mean sir?

Pada tanggal Sen, 24 Jan 2022 14.40, TechAudit ***@***.***>
menulis:
